---
functional:
  - Сайт должен иметь постраничную пагинацию 
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен видеть название, рейтинг, цену со скидкой и без неё в каталоге и карточке товара
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Возможность удалить товар из корзины
  - Пользователь должен иметь воможность успешно вернуться в корзину из каталога
  - Корзина должна храниться в сессии браузера до закрытия вкладки или обновления страницы
  - Сайт должен выполнять успешный переход к карточке товара из каталога
  - Пользователь должен иметь возможность оформить заказ
  - Сайт должен иметь страницу оплаты
  - Пользователь должен иметь возможность переключить язык интерфейса
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен работать без полной перезагрузки страниц 
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
implicit:
  - Пароли при вводе должны отображаться в зашифрованном виде
  - Оптимизированная загрузка изображений и данных на мобильных сетях
  - Кэширование изображений и товаров для повторного посещения
  - Навигация должна быть одинаково удобной на десктопе и мобильной версии
  - После оформления заказа пользователь должен получить подтверждение
  - В случае ошибки система должна показывать понятное сообщение
  - Валюта и формат даты/времени должны адаптироваться к выбранному языку
  - Тексты не должны выходить за рамки интерфейса при переключении языков
  - Состояние корзины должно сохраняться при перезагрузке страницы или повторном входе
  - Все кликабельные элементы (товар, кнопки, фильтры) должны быть функциональны
