---
- summary: |
    Убедиться, что поиск товара по ключевому слову осуществляется корректно
  status: pass
  
- summary: |
    Убедиться, что поиск товаров по категории осуществляется корректно
  status: pass
    
- summary: |
    Убедиться в корректности работы фильтрации товаров по параметру "Производитель"
  status: pass
   
- summary: |
    Убедиться, что товары, добавленные в корзину, сохраняются после перезагрузки страницы
  status: pass
  
- summary: |
    Убедиться, что информация коррекно отображается в последней версии браузера Google
  status: pass
  
- summary: |
    Убедиться, что информация коррекно отображается в последней версии браузера Mozilla Firefox
  status: pass
  
- summary: |
    Убедиться, что информация корретно отображается в последней версии браузера Safari
  status: pass
